"""Configuration file for the Sphinx documentation builder."""
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html


# ============================================================================
# Path Setup
# ============================================================================
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
import os
import sys
sys.path.insert(0, os.path.abspath('..'))


# ============================================================================
# Project Information
# ============================================================================
project = 'BRAILS++'
copyright = '2024; Licensed under BSD 3-Clause'
author = 'Barbaros Cetiner, Frank McKenna'


# ============================================================================
# General Configuration
# ============================================================================
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_design',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.napoleon',          # Supports Google/Numpy docstrings
    'sphinx.ext.imgconverter',
    'nbsphinx',
    'sphinx_copybutton',
]

autosummary_generate = True

# Prevent import errors during autodoc by mocking optional/deep ML dependencies
# autodoc_mock_imports = [
#    'torch', 'sklearn', 'lib', 'config', 'dataset',
#    'brails.utils.api',
# ]

# Add any paths that contain templates and static (such as style sheets) paths
# here, relative to this directory. The static files  are copied after the
# builtin static files, so a file named "default.css" will overwrite the
# builtin "default.css".
# templates_path = ['sphynx/templates']
# html_static_path = ['sphynx/static']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# Files/directories to exclude from build
#
# Sphinx searches the source directory recursively for reStructuredText (.rst)
# and other source files to include in the documentation. The patterns listed
# here tell Sphinx which files or directories to ignore.
#
# Reasons for exclusion can include:
# - Non-documentation files (e.g., Python scripts, setup/config files)
# - Large or binary files (e.g., images, datasets) that shouldn't be parsed
# - Directories with experimental or import-unsafe modules that will fail
#   during autodoc (e.g., require special CLI args, have heavy ML dependencies)
# - Notebooks or scripts that are too resource-intensive for ReadTheDocs builds
exclude_patterns = [
    'setup.py',
    'conf.py',
    '**/*.ipynb',
    '**/*groundingdino*',
    '**/lib/**',
    '**/train.py',
    '**/test.py',
    '**/eval*.py',
    '**/csail_segmentation_tool/**',
    '**/npid/**',
    '**/save_masked_images.py',
]

# Hide type hints in the generated documentation
#
# By default, Sphinx's autodoc extension will display Python type hints
# in function/method signatures (for example
# remove_features(features: Iterable[str]) -> bool).
# While type hints can improve code readability in source files,
# they can clutter function signatures in the rendered documentation,
# especially if the hints are verbose or contain complex generics.
#
# Setting this option to "none" hides type hints entirely from rendered docs.
# If you prefer to keep them but move them into the description instead,
# you can set this to "description". Other valid values include:
#   - "signature"   : show type hints in the function signature only
#   - "description" : show them in the parameter/return descriptions
#   - "both"        : show them in both signature and description
autodoc_typehints = "none"

# ============================================================================
# Options for HTML Output
# ============================================================================
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'

# ============================================================================
# RST substitution macros
# ============================================================================
# The `rst_prolog` variable allows you to define reStructuredText (RST) macros
# that will be automatically included at the start of every .rst source file
# processed by Sphinx.
#
# These macros simplify repetitive content and make your documentation more
# maintainable. For example, instead of typing "**fmk**" or embedding full URLs
# multiple times, you can define a substitution here and reference it anywhere
# in the docs.

rst_prolog = """
.. |fmk| replace:: **fmk**
.. |app| replace:: BRAILS++
.. |SimCenter| replace:: `SimCenter`_
.. _SimCenter: https://simcenter.designsafe-ci.org/
.. |DesignSafe| replace:: `DesignSafe`_
.. _DesignSafe: https://designsafe-ci.org
.. |br| raw:: html

    <br>

"""
